#!/bin/bash

echo "============<进入hadoop102>=========="
	ssh hadoop102 shutdown now 
echo "============<关闭hadoop102>=========="

echo "============<进入hadoop101>=========="
        ssh hadoop101 shutdown now
echo "============<关闭hadoop101>=========="

echo "============<关闭本机>==============="
	shutdown now
